logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  ## INPUTS
  features: ./outputs/causal/data/features
  tokenized: ./outputs/causal/data/tokenized
  cohort: ./outputs/causal/finetune/cohorts/full_uncensored/ # path to cohort directory

  outcomes: ./outputs/causal/finetune/outcomes
  outcome_files: # should correspond to the file names in the outcomes directory
    - OUTCOME.csv
    - OUTCOME_2.csv
    - OUTCOME_3.csv

  exposures: ./outputs/causal/finetune/outcomes
  exposure: EXPOSURE.csv

  ## OUTPUTS
  prepared_data: ./outputs/causal/finetune/prepared_data_uncensored # Save model/outputs to this folder
  #runs: ./outputs/pretraining # Use for generating a new model folder

data:
  type: finetune
  truncation_len: 256
  min_len: 0 # 0 by default
  cv_folds: 2

exposure:
  # we will convert outcomes to binary based on whether at least one outcome is in the follow up window
  n_hours_censoring: 1_000_000 # censor time after index date (negative means before)
  n_hours_start_follow_up: -1 # start follow up (considering outcomes) time after index date (negative means before)
  n_hours_end_follow_up: 10 # end follow up (considering outcomes) time after index date (negative means before)
outcome:
  n_hours_start_follow_up: -1_000_000 # start follow up (considering outcomes) time after index date (negative means before)
  n_hours_end_follow_up: null # end follow up (considering outcomes) time after index date (negative means before)
  n_hours_compliance: null # follow up time is adjusted based on compliance
  group_wise_follow_up: false # if true, then group-wise follow-up times are used
  delay_death_hours: 336 # hours to add to death time for outcomes that are coded with a delay
